language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

after_success:
  'find dist -type f -exec curl --user $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://e113743-ftp.services.easyname.eu/web/{} \;
  '
